"""
    This code should be placed on the EC2 instances running the deep learning model.
    Note: 
        1. Code assumes that the deep learning model script is located at /home/ubuntu/classifier/image_classification.py 
        2. The output file output.txt is generated by that script. 
        3. Modify the paths depending on your setup. 
        4. Also, replace 'your-response-bucket-name' with the name of the S3 bucket where the recognition results will be stored.
"""

import boto3
import subprocess
import os
import json
import yaml
import pathlib

# Set up credentialss
settings_path = pathlib.Path(__file__).parent.parent.parent.absolute() / "home/ubuntu/settings.yaml"
with open(settings_path, "r") as infile:
        CONFIG = yaml.safe_load(infile)

# put some credentials in the environment
os.environ["AWS_ACCESS_KEY_ID"] = CONFIG["aws_settings"]["AWSAccessKeyID"]
os.environ["AWS_SECRET_ACCESS_KEY"] = CONFIG["aws_settings"]["AWSSecretAccessKey"]
os.environ["AWS_DEFAULT_REGION"] = CONFIG["aws_settings"]["AWSDefaultRegion"]

sqs = boto3.resource('sqs')
request_queue = sqs.get_queue_by_name(QueueName='requestQueue')
response_queue = sqs.get_queue_by_name(QueueName='responseQueue')
response_queue_url = response_queue.url
response_bucket = 'outputbucket546'

while True:
    # Receive messages from the request queue
    messages = request_queue.receive_messages(MaxNumberOfMessages=2, WaitTimeSeconds=20)
    if messages:
        # Process each message
        for message in messages:
            image_key = message.body
            image_name = os.path.splitext(os.path.basename(image_key))[0]
            response_key = image_name + '.JPEG'

            # Run the deep learning model on the image
            subprocess.run(['python3', pathlib.Path(__file__).parent.parent.parent.absolute() / "home/ubuntu/image_classification.py", image_key])

            # Read the result from the output file
            with open('output.txt', 'r') as f:
                result = f.read().strip()

            # Upload the result to S3
            s3 = boto3.resource('s3')
            response_object = s3.Object(response_bucket, response_key)
            response_object.put(Body=result)

            # Send a message to the web tier with results from image recognition
            res_message = {response_key: result}
            sqs_message = sqs.Queue(response_queue_url).send_message(MessageBody=json.dumps(res_message))

            # Delete the message from the queue
            message.delete()
