aws_settings:
  AWSAccessKeyID: ****
  AWSDefaultRegion: us-east-1
  AWSSecretAccessKey: ****
  ImageId: ami-0557a15b87f6559cf
  ImageUser: ubuntu
  InstanceType: t2.micro
  KeyName: ****
  KeyPath: ~/.ssh/****